function UseCustomFeedSelection() {
  const feedSelection = [
    {
      category: "Sports",
      topics: [
        "Football",
        "Basketball",
        "Tennis",
        "Cricket",
        "Baseball",
        "Hockey",
        "Golf",
        "Rugby",
        "Athletics",
        "Mixed Martial Arts",
      ],
    },
    {
      category: "Politics",
      topics: [
        "Elections",
        "Policies",
        "International Relations",
        "Political Parties",
        "Legislation",
        "Public Opinion",
        "Government",
        "Political Analysis",
      ],
    },
    {
      category: "Stock Market",
      topics: [
        "Investing",
        "Market Trends",
        "Financial News",
        "Stock Analysis",
        "Cryptocurrency",
        "Investment Strategies",
        "Market Predictions",
        "Dividend Stocks",
      ],
    },
    {
      category: "AI",
      topics: [
        "Machine Learning",
        "Natural Language Processing",
        "Computer Vision",
        "Deep Learning",
        "AI Ethics",
        "Robotics",
        "AI in Healthcare",
        "AI in Business",
      ],
    },
    {
      category: "Programming",
      topics: [
        "JavaScript",
        "Python",
        "Java",
        "C#",
        "Ruby",
        "Go",
        "Swift",
        "Kotlin",
        "HTML/CSS",
        "SQL",
      ],
    },
    {
      category: "Fashion Business",
      topics: [
        "Trends",
        "Sustainability",
        "Marketing Strategies",
        "E-commerce",
        "Brand Management",
        "Fashion Shows",
        "Consumer Behavior",
        "Retail Strategies",
      ],
    },
    {
      category: "Science",
      topics: [
        "Physics",
        "Biology",
        "Chemistry",
        "Astronomy",
        "Earth Science",
        "Environmental Science",
        "Genetics",
        "Neuroscience",
      ],
    },
    {
      category: "Health",
      topics: [
        "Nutrition",
        "Fitness",
        "Mental Health",
        "Public Health",
        "Healthcare Policy",
        "Disease Prevention",
        "Medical Research",
        "Wellness",
      ],
    },
    {
      category: "Technology",
      topics: [
        "Gadgets",
        "Software Development",
        "Cybersecurity",
        "Blockchain",
        "Cloud Computing",
        "Virtual Reality",
        "Augmented Reality",
        "Internet of Things (IoT)",
      ],
    },
    {
      category: "Business",
      topics: [
        "Entrepreneurship",
        "Marketing",
        "Finance",
        "Human Resources",
        "Business Strategy",
        "Startups",
        "Corporate Culture",
        "Business Ethics",
      ],
    },
    {
      category: "Travel",
      topics: [
        "Destinations",
        "Travel Tips",
        "Cultural Experiences",
        "Adventure Travel",
        "Travel Insurance",
        "Budget Travel",
        "Luxury Travel",
        "Travel Photography",
      ],
    },
    {
      category: "Entertainment",
      topics: [
        "Movies",
        "Television",
        "Music",
        "Theater",
        "Video Games",
        "Books",
        "Celebrity News",
        "Streaming Services",
      ],
    },
    {
      category: "Lifestyle",
      topics: [
        "Home Decor",
        "Cooking",
        "Gardening",
        "Personal Finance",
        "Sustainable Living",
        "Hobbies",
        "Fashion",
        "Wellness",
      ],
    },
    {
      category: "Education",
      topics: [
        "Online Learning",
        "Study Tips",
        "Educational Technology",
        "Curriculum Development",
        "Higher Education",
        "K-12 Education",
        "Adult Learning",
        "Special Education",
      ],
    },
    {
      category: "History",
      topics: [
        "Ancient Civilizations",
        "World Wars",
        "Cultural History",
        "Historical Figures",
        "Modern History",
        "Economic History",
        "Political History",
        "Social Movements",
      ],
    },
    {
      category: "Environment",
      topics: [
        "Climate Change",
        "Sustainability",
        "Conservation",
        "Wildlife Protection",
        "Renewable Energy",
        "Pollution",
        "Environmental Policy",
        "Ecology",
      ],
    },
    {
      category: "Parenting",
      topics: [
        "Child Development",
        "Education",
        "Parenting Tips",
        "Family Activities",
        "Work-Life Balance",
        "Health and Nutrition",
        "Discipline Strategies",
        "Teen Parenting",
      ],
    },
  ];

  return feedSelection;
}

export default UseCustomFeedSelection;
